In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("../dataset/data.xlsx")

In [3]:
df.columns

Index(['client_id', 'fam', 'ism', 'sharif', 'pseriya', 'praqam', 'document_id',
       'pkb', 'pqb', 'ptm', 'pnfl', 'phone1', 'phone2', 'birth_date', 'jins',
       'viloyat_id', 'tuman_id', 'mfy_id', 'address', 'roy_address', 'orientr',
       'work_type', 'kasb', 'work_place_address', 'work_place_phone',
       'work_place_phone_owner', 'lavozim', 'salary', 'card_status',
       'work_place', 'work_place_name', 'client_status', 'status', 'tavsif',
       'filial_id', 'user_id', 'created_at', 'updated_at', 'deleted_at',
       'work_type_client_sorovnoma_finances.xlsx',
       'kasb_client_sorovnoma_finances.xlsx',
       'work_place_address_client_sorovnoma_finances.xlsx',
       'work_place_phone_client_sorovnoma_finances.xlsx',
       'work_place_phone_owner_client_sorovnoma_finances.xlsx',
       'lavozim_client_sorovnoma_finances.xlsx',
       'salary_client_sorovnoma_finances.xlsx',
       'card_status_client_sorovnoma_finances.xlsx',
       'work_place_client_sorovnoma_finances.xlsx', 'work_tashkilot',
       'user_id_client_sorovnoma_finances.xlsx',
       'created_at_client_sorovnoma_finances.xlsx',
       'updated_at_client_sorovnoma_finances.xlsx',
       'deleted_at_client_sorovnoma_finances.xlsx', 'fio', 'qarindosh_status',
       'ish_status', 'ish_faoliyat', 'ish_manzil',
       'salary_client_sorovnoma_oilas.xlsx',
       'user_id_client_sorovnoma_oilas.xlsx',
       'created_at_client_sorovnoma_oilas.xlsx',
       'updated_at_client_sorovnoma_oilas.xlsx',
       'deleted_at_client_sorovnoma_oilas.xlsx', 'oila_status',
       'oila_azo_soni', 'home_type', 'home_owner', 'main_xarajat',
       'user_id_client_sorovnoma_qoshimchas.xlsx',
       'created_at_client_sorovnoma_qoshimchas.xlsx',
       'updated_at_client_sorovnoma_qoshimchas.xlsx',
       'deleted_at_client_sorovnoma_qoshimchas.xlsx', 'model_id', 'narxi',
       'soni', 'summa', 'izoh', 'user_id_client_sorovnoma_tovars.xlsx',
       'created_at_client_sorovnoma_tovars.xlsx',
       'updated_at_client_sorovnoma_tovars.xlsx',
       'deleted_at_client_sorovnoma_tovars.xlsx', 'muddat', 'btolov',
       'marketing', 'xodim', 'client_status_client_sorovnoma_zakazs.xlsx',
       'izoh_client_sorovnoma_zakazs.xlsx',
       'user_id_client_sorovnoma_zakazs.xlsx',
       'created_at_client_sorovnoma_zakazs.xlsx',
       'updated_at_client_sorovnoma_zakazs.xlsx'],
      dtype='object')

In [4]:
selected_columns = [
    "client_id", "fam", "ism", "sharif", "pseriya", "praqam", "pnfl", "phone1", "phone2", "birth_date", "jins", "viloyat_id","tuman_id", "mfy_id", "client_status", "status", "work_type_client_sorovnoma_finances.xlsx",
    "kasb_client_sorovnoma_finances.xlsx", "work_place_phone_client_sorovnoma_finances.xlsx",
    "work_place_phone_owner_client_sorovnoma_finances.xlsx", "lavozim_client_sorovnoma_finances.xlsx", "salary_client_sorovnoma_finances.xlsx", "ish_faoliyat", "salary_client_sorovnoma_oilas.xlsx", "ish_status", "oila_status", "oila_azo_soni", "home_type", "home_type", "home_owner", "main_xarajat", "narxi", "summa"
]

In [5]:
extracted_data = df[selected_columns]

In [6]:
extracted_data

,client_id,fam,ism,sharif,pseriya,praqam,pnfl,phone1,phone2,birth_date,...,salary_client_sorovnoma_oilas.xlsx,ish_status,oila_status,oila_azo_soni,home_type,home_type,home_owner,main_xarajat,narxi,summa
0,3,Imomnazarov,Islomjon,Ramishjon o'g'li,AC,2507350,52112017050022,951552128.0,NaN,2001-12-21,...,6000000.0,1.0,2,5,2.0,2.0,1.0,1200000,15930000.0,15930000.0
1,4,Meliqo`ziyeva,Muslimaxon,Farxodjon qizi,AA,8312668,40207954320028,912056205.0,NaN,1995-02-07,...,3500000.0,1.0,1,7,1.0,1.0,1.0,3500000,5309000.0,5309000.0
2,5,Asqarova,Dilshoda,Ergashevna,AC,2979026,40307864230038,905674009.0,NaN,1986-07-03,...,2500000.0,1.0,2,3,2.0,2.0,1.0,1000000,6708000.0,6708000.0
3,6,Nosirov,Azizbek,Kozimjon O'g'li,AB,1732823,31406914250018,932141491.0,NaN,1991-06-14,...,9000000.0,1.0,1,6,1.0,1.0,1.0,2400000,984256.0,984256.0
4,7,Akramov,Alixon,Akbarovich,AA,6311205,30503774320086,905568080.0,NaN,1977-03-05,...,3000000.0,1.0,1,6,1.0,1.0,1.0,2400000,370000.0,370000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6561,6902,Isakova,Muyassar,Anvarjanovna,AC,1159792,40405837050019,942720010.0,911554836,1983-05-04,...,NaN,1.0,1,6,1.0,1.0,1.0,2400000,2736000.0,2736000.0
6562,6903,Uzoqova,Sojida,Turdaliyevna,AA,8189646,41912905910010,990511591.0,770163608 Jiyani/t,1990-12-19,...,1500000.0,1.0,1,7,1.0,1.0,1.0,2800000,6732000.0,6732000.0
6563,6904,Soliyeva,Barno,Saminovna,AD,7310330,42708664320064,916858974.0,916860845 t/u,1966-08-27,...,2500000.0,1.0,1,6,2.0,2.0,1.0,3000000,1380000.0,1380000.0
6564,6905,Qurbonova,Zulfiya,Abduxamedovna,AB,7422596,42603647020022,882042070.0,998972062070,1964-03-26,...,750000.0,1.0,1,5,1.0,1.0,1.0,2500000,7152000.0,7152000.0
6565,6906,Evatova,Feruza,Kaxramanovna,AC,2753361,42001812120027,937694488.0,99 997 68 82 O'g'illari/t,1981-01-20,...,5000000.0,1.0,1,3,2.0,2.0,1.0,1200000,7668000.0,7668000.0

In [7]:
extracted_data.to_csv("extracted_data.csv", index=False)